### ISSUE TITLE
Issue with code output

### ISSUE THREAD

**Issue by 2fst4u** [amshar21/hibpcli#1]
Running the script on a test file containing the following:

password
12345
'password
'password'
"password
"password"

results in the following output:

- HaveIBeenPwned-cli
- github.com/Codeshift3r

- Total passwords: 6
- Total tasks: 2
- Password per task: 3
- Splitting files...

' was found 53493 times
' was found 31903 times
' was found 1 times
' was not found
' was not found
- '"password"' was found 142 times

- Task completed

As you can see it seems to be cutting off the words from the input. I'm not sure if this is in-turn impacting the input and not actually running the correct words through.

**Comment by amshar21** [comment]
Hi, I was able to reproduce your problem with wordlist input from windows-style newline (`\r\n`).
Try using input from unix-style newline (`\n`) to get it to work properly.
As a proactive measure I'll just add a dos2unix line to do the conversion automatically.
Im sure there is a pure bash way of doing it but so far many that i've tried simply doesn't work 100% of the time.

**Comment by 2fst4u** [comment]
Sounds good, thanks.
